### ISSUE TITLE
ParquetSharp can produce invalid files without throwing an exception when ran without enough memory.

### ISSUE THREAD

**Issue by TobyShaw** [G-Research/ParquetSharp#104]
Context: We saw 2 reports in the last week of invalid Parquet files being written without any exception reported by the library. This is especially annoying from the perspective of jobs on a compute farm, because we interpret the process as being successful, therefore assuming the parquet file is valid, therefore causing all jobs which consume this file to fail.

We are using the AppendBufferedRowGroup API, and were restricting the memory via job objects.

I have tested this locally, with a parquet-writing process which runs processes attached to job objects, ramping up the memory limit until it stopped throwing OutOfMemory exceptions. As expected, the first few files produced from this approach are invalid. The most obvious explanation is that there is an exception thrown in the Dispose method of either ColumnWriter or RowGroupWriter, which is swallowed:

- https://github.com/G-Research/ParquetSharp/blob/master/csharp/ColumnWriter.cs
- https://github.com/G-Research/ParquetSharp/blob/master/csharp/RowGroupWriter.cs

This is consistent with my experiment, as the first N tests threw OOM exceptions (because it's not swallowed in AppendRowGroup or WriteBatch), then there was a set which produced broken files silently (when all the Writes succeeded, but the Dispose did not), then all future ones were valid parquet files.

I could definitely produce more evidence towards reproducing this bug, namely:
- The dodgy parquet files produced
- The repro code

Please push me for this if you think these would be helpful.

**Comment by GPSnoopy** [comment]
Looks like the same exception logic is used by Parquet C++ itself.
```c++
ParquetFileWriter::~ParquetFileWriter() {
  try {
    Close();
  } catch (...) {
  }
}
```

It would follow that the proper way to use Parquet C++ is to explicitly call `Close()` on the file writer instead of silently disposing of it.

Looking at the code, the `RowGroupWriter` and the `ColumnWriter` destructors do not do anything in C++. Calling the `AppendRowGroup()` and `NextColumn()` methods effectively close the previously opened writers, and so does the `Close()` method on the main `ParquetFileWriter`.

I'm adding the `Close()` method on `ParquetFileWriter` in C#, and will update examples and documentation accordingly.

**Comment by TobyShaw** [comment]
Are you implying that you will match C++'s behaviour for the destructors of RowGroupWriter/ColumnWriter doing nothing? Or will they keep calling Close (I'm not sure if this is require for backwards compatibility reasons). I think either are valid as a consumer.

Thanks for the extremely fast turnaround on this issue report!

**Comment by GPSnoopy** [comment]
You are correct. With this PR, it'll match the C++ behaviour. I have updated the README examples to reflect this.

I do not think this will impact backward compatibility.
