### ISSUE TITLE
Creating a Parquet file with an empty row group doesn't work anymore

### ISSUE THREAD

**Issue by GPSnoopy** [G-Research/ParquetSharp#110]
It seems that the upgrade from Arrow 0.15.1 to Arrow 0.16 has caused a regression when writing a Parquet file with an empty row group (i.e. a row group with zero rows).

The following C# .NET Core 3.1 code works with ParquetSharp 2.0.2, but fails with 2.1.0-beta1 when reading the file.

```csharp
public static void Main()
{
    try
    {
        WriteEmptyRowGroup();
        ReadEmptyRowGroup();
    }
    catch (Exception exception)
    {
        Console.WriteLine("ERROR: " + exception);
    }
}

private static void WriteEmptyRowGroup()
{
    var columns = new Column[]
    {
        new Column<int>("Id"), 
        new Column<float>("Value")
    };

    using var fileWriter = new ParquetFileWriter("empty_row_group.parquet", columns);
    using var groupWriter = fileWriter.AppendRowGroup();

    // Uncomment to get the actual write exception
    //groupWriter.Close();
}

private static void ReadEmptyRowGroup()
{
    using var fileReader = new ParquetFileReader("empty_row_group.parquet");
    using var groupReader = fileReader.RowGroup(0);

    if (groupReader.MetaData.NumRows != 0) throw new InvalidDataException($"expected 0 rows (got {groupReader.MetaData.NumRows})");
    if (groupReader.MetaData.NumColumns != 2) throw new InvalidDataException($"expected 2 columns (got {groupReader.MetaData.NumColumns}");

    using var idReader = groupReader.Column(0);
    using var valueReader = groupReader.Column(1);
}
```

Calling `groupWriter.Close()` or `fileWriter.Close()` in either Arrow 0.15.1 and 0.16 bubbles up an exception that otherwise gets gobbled by the C++ destructors: `'Only -1 out of 2 columns are initialized'`. The difference is that in Arrow 0.15.1 the generated file is still readable, while in 0.16 it is not.

The is not the first attempt to address this issue. See the following ticket:
https://issues.apache.org/jira/browse/PARQUET-1378

IMHO There are several issues here:
- The generated file should be readable.
- No exception should be thrown when calling `Close()` on an empty row group. This is not an exceptional case, creating an empty row group is logically correct (e.g. a table with no rows, an empty array, an empty collection, etc).
- This has clearly regressed, which means there are not enough unit tests around this area in Arrow.
- Bonus for unit tests around Parquet files with zero columns.

**Comment by tpboudreau** [comment]
I agree that creating an empty row group is inoffensive and should not throw an exception.  Also, this API has some ergonomics issues.

Two observations:

1.  I was able avoid the spurious "not initialized" exception while still successfully writing an empty (i.e., no rows) row group by visiting each column in the empty row group sequentially using RowGroupWriter::NextColumn() -- just as you would if you had data to write -- and simply not writing values to the returned ColumnWriter.  AFAICT, this resulted in a well-formed (readable) parquet file with no data, but correct metadata, as desired.  I haven't found it documented anywhere, but it's possible that visiting each column like this is a requirement of the API (all the tests and examples I could find do this).  So if it's practical for you to ensure that this occurs in your usage, this might be an easy workaround.  I haven't fully untangled the code to see how feasible or desirable it would be to have, say, the RowGroupWriter::Close() method auto-iterate the columns if there's no data (as a convenience feature), but it doesn't appear to be trivial.

2.  Even when I did reproduce the spurious exception, I got a corrupted parquet file result only if I also failed to close the RowGroupWriter.  In other words, if I called RowGroupWriter::Close() and it threw the exception, the resulting file was readable.  If I skipped calling RowGroupWriter::Close() but called ParquetFileWriter::Close() and it threw the exception, the file was corrupt.  It would not be surprising if the chained Close() and Finish() calls in these classes shifted recently as there have been several commits (especially related to adding compression and encryption) that have rejiggered the file termination mechanics.  But it seems you get the better result if you call close() on both objects.

Below is a the code I wrote to reproduce the problem(s) and demonstrate the workaround, in case that helps.  It directly calls the upstream Parquet C++ library (tested on Linux, I don't have a full Windows dev setup).  The loop at line 42-45 is what prevents the exception throw.

[example_code.txt](https://github.com/G-Research/ParquetSharp/files/4258776/example_code.txt)

I'm not going to open an issue in the upstream library until I hear back, because the only thing that's obviously wrong with the upstream is the error message (which is always off by one in the number of columns not visited/initialized).  Otherwise it seems like it might be just non-contract API behavior that changed.  But I could be missing or misunderstanding something, so please let me know.

**Comment by GPSnoopy** [comment]
Hi @tpboudreau,

Thanks to your very detailed investigation, I believe I was able to fix the `RowOriented.ParquetRowWriter`. It now writes every columns, even if they are empty. See PR #111. This should unblock my colleagues to upgrade ParquetSharp.

I think it is worth raising an issue with Parquet C++, if only to get better documentation on the correct API usage and put that documentation in an obvious place.

Regarding point 2, IMHO calling RowGroupWriter::Close or relying on the destructor should lead to the same result. At least it's a reasonable expectation. So indeed possible regression there. Again, I think it's worth mentioning to Parquet C++ people, if only to get better documentation on the proper API usage. The ParquetFileWriter doc-strings imply it is a regression or that there is at least reasonable doubt (also note that these methods returns non-scoped pointers, with no-RAII patterns implied in any way).

```c++
  /// Construct a RowGroupWriter with an arbitrary number of rows.
  ///
  /// Ownership is solely within the ParquetFileWriter. The RowGroupWriter is only valid
  /// until the next call to AppendRowGroup or AppendBufferedRowGroup or Close.
  RowGroupWriter* AppendRowGroup();

  /// Construct a RowGroupWriter that buffers all the values until the RowGroup is ready.
  /// Use this if you want to write a RowGroup based on a certain size
  ///
  /// Ownership is solely within the ParquetFileWriter. The RowGroupWriter is only valid
  /// until the next call to AppendRowGroup or AppendBufferedRowGroup or Close.
  RowGroupWriter* AppendBufferedRowGroup();
```

Perhaps it is the exception-safety documentation that is lacking?

In general, through my own experience it feels like the API is schizophrenic when it comes to flushing writes and releasing resources. It doesn't seem to know whether it should rely on explicit calls to Close() or the destructors. If one should always rely on the explicit Close() calls, then the destructors should never write a valid file without them? (probably a valid assumption on ParquetFileWriter at least, but not very user friendly if enforced on RowGroupWriter and ColumnWriter).

**Comment by tpboudreau** [comment]
I don't think I disagree with anything you've said, @GPSnoopy .

1.  The documentation is insufficient regarding the requirement (or not) of visiting each column in every row group.  I'll dig a little more to make sure I haven't missed anything, and then open an issue and/or submit a PR to clarify the docs (or get corrective feedback).

2.  It's unclear who is responsible for calling the Close() method on the RowGroupWriter: the borrowing caller or the owning FileWriter.  Since it's unspecified, it's certainly not unreasonable to assume that the owner will ensure the proper disposition of it's own resources.  I'll see if I can figure out why the behavior changed and what the next steps should be there (better docs at a minimum I would think).  

The more you look at it, the more awkward this API seems.

**Comment by GPSnoopy** [comment]
Closing as I'm happy with the state of our implementation; most use cases should be covered.
