### ISSUE TITLE
ParquetSharp 2.0.2 writes parquet files SPARK and pyarrow cannot open

### ISSUE THREAD

**Issue by GitHubWhileAtWork** [G-Research/ParquetSharp#117]
I recently upgraded to ParquetSharp 2.0.2, but found both SPARK and PyArrow where unable to read the parquet files which it wrote.  SPARK would throw an lz4 decompression error, while pyarrow would (depending on the version) return errors like:

ArrowIOError: Couldn't deserialize thrift: don't know what type: 
Deserializing page header failed.

FastParquet would (depending on the version) return errors like:

line 71, in lz4_decompress
return lz4.block.decompress(data, uncompressed_size=uncompressed_size)
TypeError: an integer is required (got type NoneType)

All files were written using default (Snappy) compression.

Reverting to ParquetSharp 2.0.1 and rewriting all parquet files resolved all my issues.

**Comment by GPSnoopy** [comment]
Hi @GitHubWhileAtWork ,

In 2.0.2 we've switched to LZ4 compression by default instead of Snappy. We found out that in all our use cases, the resulting Parquet LZ4 files were smaller and faster to read and write. In hindsight, this might not have been the best decision as a lot of Parquet libraries currently do not support LZ4 (as you have yourself noticed).

Note that the compression mode is an argument passed in `ParquetFileWriter` constructors and/or in `WriterProperties`. So you can explicitly set it to Snappy. This is what we do when we write files that need to be consumed by Apache Spark.

The PyArrow error is more disturbing given that both PyArrow and Parquet C++ are part of the same library (Apache Arrow) and therefore use the same Parquet loading implementation. Which version of PyArrow are you using? ParquetSharp 2.0.2 uses Arrow 0.15.1, so I would suggest to use that PyArrow version. Also, we have noticed a few critical bugs with Arrow 0.16, so I would personnaly not recommend using 0.16 just yet.

I can confirm that internally for our use cases, we are able to read ParquetSharp 2.0.2 files with PyArrow.

Keep me posted.

Best regards,
Tanguy

**Comment by GitHubWhileAtWork** [comment]
Hi Tanguy

Many thanks for the explanation.  

Failure opening the files was experienced on pyarrow 0.13.0 and pyarrow 0.16.0.  I see your recommendation is to use 0.15.1.   It makes sense that we wouldn't have tried 0.15.1 after observing failures with two versions either side.  Unfortunately I have overwritten all the files, so I can't test until I update to 2.0.2 again.

And you have also noticed that SPARK requires snappy, so all is making sense.  

At some point in the future we'll upgrade to 2.0.2 and set the snappy compression explicitly as the "default option" on our end.

Thanks again
Andrew
