### ISSUE TITLE
Make SchemaNodes interned to allow reference equality

### ISSUE THREAD

**Issue by UncleMattHope** [G-Research/ParquetSharp#175]
If you attempt to do something like this:
```
public static string GetColumnIndexFromName(ParquetFileReader reader, string name)
{
    foreach (var i in Enumerable.Range(0, reader.FileMetaData.Schema.NumColumns))
    {
        var column = _reader.FileMetaData.Schema.Column(i);
        var node = column.SchemaNode;
        while (node.Parent != reader.FileMetaData.Schema.SchemaRoot)
        {
            node = node.Parent;
        }
        if (node.Name == name)
        {
            return i;
        }
   }
   throw new KeyNotFoundException($"Failed to find column {name}");
}
```
It will fail to work as inteneded because the Nodes are not reference equal.
Workarounds include checking the name ("schema" or for FieldId 0, but those are specific to the schema root), it would be nice to be able to just test the nodes for equality including via reference equality.

**Comment by GPSnoopy** [comment]
Unfortunately, due to the native to managed PInvoke mapping, it seems quite hard to provide reference equality in C# matching the C++ behaviour.

I suggest to use `Node.Equals()` instead. I've cleaned up the implementation with PR #182 but be aware that the comparison is _O(n)_ if the node is a `GroupNode` (where _n_ is the number of direct and indirect children), which is probably not what you want.
