### ISSUE TITLE
Add support for round tripping .Net decimal type as a DECIMAL logical type

### ISSUE THREAD

**Issue by SpencerBullent** [G-Research/ParquetSharp#18]

**Comment by GPSnoopy** [comment]
PR #21 adds support for an internal Decimal96 representation. This corresponds to Parquet 28 digits precision, which is also .NET System.Decimal precision.

I'll deliberately leave 32-bits and 64-bits representations out of the scope from this issue, as round-tripping System.Decimal should now be possible. Further work on this might be desirable for better interop with other libraries. Please raise a new issue if needed.

**Comment by GPSnoopy** [comment]
Comments from 1.4.0.2-beta1:

- Decimal.MinValue/MaxValue do not round trip. This is because we are storing decimals on 96 bits, but C# actual uses 97 bits (one extra bits for the sign).
- The _scale_ parameter should not have a default value. It confuses users. Let it be exposed as a decision to be made by the user rather than assume 0 is a good default.
- If scale * value is too big, C# will throw OverflowException in Decimal96 ctor. Maybe be a little more informative?

**Comment by GPSnoopy** [comment]
Unit test for Min/Max:

```
            var list = new List<decimal>{0, 1};
            for (int i = 0; i != 28; ++i)
            {
                list.Add(list.Last() * 10);
            }

            list.Add(decimal.MaxValue);
```

**Comment by GPSnoopy** [comment]
PR #24 moves back to 128-bits, which ensures proper round tripping of all possible System.Decimal values. It also takes into account the feedback from beta1.
