### ISSUE TITLE
Question: Append RowGroup for existing file

### ISSUE THREAD

**Issue by jiatao99** [G-Research/ParquetSharp#213]
Do you have any sample code to append RowGroup for existing parquet file?

I use File.Open with AppendMode, however, I got not implementation exception

Thanks for this great project

**Comment by GPSnoopy** [comment]
Hi @jiatao99,

I'm not sure C++ Arrow (on which ParquetSharp is built) allows to append more rows/row-groups to an existing file. If you find something in C++ Arrow that is missing in ParquetSharp and would allow you to do this, do give us a shout.

Otherwise, I think you'll have to create a new parquet file, copy the existing rows to the new file and add the new rows afterwards before closing the writer to the new file.

**Comment by jiatao99** [comment]
Hi @GPSnoopy,

Thanks for your quick reply. What's most efficient way to copy data from source to target? Do I have to deserialize everything and serialize it again?

I found there is a property in RowGroupMetaData.ColumnChunkMetaData.  Can it be just passthrough can copy to target file or something like that?

**Comment by GPSnoopy** [comment]
In my experience you pretty much have to:
- Copy the schema (check the `DeepClone` methods on `Node` to help you there).
- Copy the key-value metadata.
- Copy any writer properties you want to keep (e.g. compression).
- Read the values, and write them back to the new file.

It's not a great experience. We had to do it ourself for an internal tool that merges multiple parquet files into one.

**Comment by jiatao99** [comment]
1. I saw there are DeepClone method on the Node. However, after clone, which API should I use to copy it into the writer?
2. For read values and copy it back, do you mean direct copy stream over or I have to deserialize to c# array and serialize it back to the target stream? 

> In my experience you pretty much have to:
> 
> * Copy the schema (check the `DeepClone` methods on `Node` to help you there).
> * Copy the key-value metadata.
> * Copy any writer properties you want to keep (e.g. compression).
> * Read the values, and write them back to the new file.
> 
> It's not a great experience. We had to do it ourself for an internal tool that merges multiple parquet files into one.

**Comment by GPSnoopy** [comment]
1. `ParquetFileWriter` has several constructors that take the schema directly as a `GroupNode`.  AFAIK you're guaranteed that the schema root node you get from the reader is also a `GroupNode`. So you can cast after cloning.
2. Yes. Read them into an array buffer and write them as you go. You can do this in batch, no need to read all values in one go.

**Comment by engaged73016** [comment]
Hello,

I am a new user of ParquetSharp, and I am very interested in this topic of "pseudo-appending" a file by copying the schema as GroupNode, and copying values via array buffer in batch.
I have not had much success so far. Would anyone who's done it be kind enough to share some sample code?

Thanks, and thanks for this very useful project! 


> 1. `ParquetFileWriter` has several constructors that take the schema directly as a `GroupNode`.  AFAIK you're guaranteed that the schema root node you get from the reader is also a `GroupNode`. So you can cast after cloning.
> 2. Yes. Read them into an array buffer and write them as you go. You can do this in batch, no need to read all values in one go.

**Comment by adamreeve** [comment]
Hi @engaged73016, I don't have any example code handy that does this, but if you can provide the code you've tried and explain what problems you've encountered I should be able to help.

**Comment by pavlexander** [comment]
Arrording to [this article](https://aseigneurin.github.io/2017/03/14/incrementally-loaded-parquet-files.html) there is a proccess of asding partitions to an existing file.

> Now, we can use a nice feature of Parquet files which is that you can add partitions to an existing Parquet file without having to rewrite existing partitions. That is, every day, we will append partitions to the existing Parquet file. With Spark, this is easily done by using .mode("append") when writing the DataFrame.

I was wondering if i understood the message correctly and whether this library (ParquetSharp) supports the append operation as explained in that article?

If i understood correctly - you can basically append new data in batches to an existing file, this does not mean,however, that the resulting file will be optimized fully.i.e. each partition gets compresed separately. Is that it?

**Comment by adamreeve** [comment]
Hi @pavlexander, in theory yes you could append data to existing files. You can see the layout of the format at https://github.com/apache/parquet-format/#file-format. You could append new row groups, overwriting the existing footer, then write a new footer at the end that contains information about all of the previous row groups and the newly appended ones. And the Parquet format already compresses buffers individually so I don't believe the resulting file would be any different to one written by writing separate row groups normally. The fastparquet library has an append mode that implements this behaviour: https://fastparquet.readthedocs.io/en/latest/api.html#fastparquet.write

But this is not something that is supported by the Apache C++ Parquet library that ParquetSharp uses, so if you'd like this feature in ParquetSharp it would be best to raise an issue to request this in the C++Parquet library at https://github.com/apache/arrow first, or comment on this existing issue that's labeled Python but would also require support at the C++ level: https://github.com/apache/arrow/issues/33362. This was also raised a while ago in https://issues.apache.org/jira/browse/PARQUET-1022 though, and closed as won't fix due to the extra complication this would require, so I wouldn't hold out a lot of hope that it will happen.

I'm also not sure that Spark actually does append row groups to existing files. I'm not very familiar with Spark or the Java parquet-mr library, but based on this StackOverflow comment, https://stackoverflow.com/questions/39234391/how-to-append-data-to-an-existing-parquet-file/74206625#comment87190416_42140475, and the fact that the article you linked says "When we say “Parquet file”, we are actually referring to multiple physical files, each of them being a partition", it sounds like Spark actually just writes new files rather than appending row groups to a single existing file.

It seems like most people handle the problem of appending Parquet data by using datasets containing multiple Parquet files and then querying them all when reading the data, as this is much simpler to implement than appending to an existing file.

**Comment by pavlexander** [comment]
> Hi @pavlexander, in theory yes you could append data to existing files. You can see the layout of the format at https://github.com/apache/parquet-format/#file-format. You could append new row groups, overwriting the existing footer, then write a new footer at the end that contains information about all of the previous row groups and the newly appended ones. And the Parquet format already compresses buffers individually so I don't believe the resulting file would be any different to one written by writing separate row groups normally. The fastparquet library has an append mode that implements this behaviour: https://fastparquet.readthedocs.io/en/latest/api.html#fastparquet.write
> 
> But this is not something that is supported by the Apache C++ Parquet library that ParquetSharp uses, so if you'd like this feature in ParquetSharp it would be best to raise an issue to request this in the C++Parquet library at https://github.com/apache/arrow first, or comment on this existing issue that's labeled Python but would also require support at the C++ level: [apache/arrow#33362](https://github.com/apache/arrow/issues/33362). This was also raised a while ago in https://issues.apache.org/jira/browse/PARQUET-1022 though, and closed as won't fix due to the extra complication this would require, so I wouldn't hold out a lot of hope that it will happen.
> 
> I'm also not sure that Spark actually does append row groups to existing files. I'm not very familiar with Spark or the Java parquet-mr library, but based on this StackOverflow comment, https://stackoverflow.com/questions/39234391/how-to-append-data-to-an-existing-parquet-file/74206625#comment87190416_42140475, and the fact that the article you linked says "When we say “Parquet file”, we are actually referring to multiple physical files, each of them being a partition", it sounds like Spark actually just writes new files rather than appending row groups to a single existing file.
> 
> It seems like most people handle the problem of appending Parquet data by using datasets containing multiple Parquet files and then querying them all when reading the data, as this is much simpler to implement than appending to an existing file.

thank you very much for a very detailed response!

**Comment by adamreeve** [comment]
I'm going to close this as answered, if the Apache C++ Parquet library gets support for appending data to existing files then we can reopen this and look at adding support in ParquetSharp.
