### ISSUE TITLE
DateTime value written is different to the actual Ticks

### ISSUE THREAD

**Issue by vikramrkin** [G-Research/ParquetSharp#227]
Hi G-Researchers/contributers,

I am facing an issue with writing and reading back DateTime values. After writing a DateTime, when I read it back, the Ticks is not same as the original DateTime object. Here is a failing test:

```
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.IO;
using ParquetSharp;
using ParquetSharp.IO;

[TestClass]
public class ParquetDateTest
{
    [TestMethod]
    public void DateTest()
    {
        var ms = new MemoryStream();
        var columns = new Column[] { new Column(typeof(DateTime), "d1") };
        var managedOutputStream = new ManagedOutputStream(ms);

        // Date value I want to write to Parquet
        var date = DateTime.UtcNow;

        using (var writer = new ParquetFileWriter(managedOutputStream, columns))
        {
            using (var rgWriter = writer.AppendRowGroup())
            {
                var dateColWriter = rgWriter.NextColumn().LogicalWriter<DateTime>();
                dateColWriter.WriteBatch(new DateTime[] { date });
            }
        }

        ms.Position = 0;
        var dates = new DateTime[1];
        var managedRandomAccessFile = new ManagedRandomAccessFile(ms);
        using (var reader = new ParquetFileReader(managedRandomAccessFile))
        {
            using (var rgReader = reader.RowGroup(0))
            {
                using (var colReader = rgReader.Column(0))
                {
                    using (var logicalReader = colReader.LogicalReader<DateTime>())
                    {
                        logicalReader.ReadBatch(dates, 0, 1);
                    }
                }
            }
        }

        // The two ticks are not same in this case. The last digit of Ticks read from Parquet is always 0
        Assert.AreEqual(date.Ticks, dates[0].Ticks);
    }
}
```

As an example, Ticks from .Net DateTime object is 637721234513850344, where as the Ticks from Parquet read DateTime is 637721234513850340.

Please can you help me understand why this is happening?

Thanks
Vikram

**Comment by GPSnoopy** [comment]
Hi @vikramrkin,

This is because by default `new Column<DateTime>("d1")` gives you millisecond precision, and the ticks in your example contains sub-milliseconds (400 nanoseconds to be exact, as per `TimeSpan.TicksPerSecond = 10_000_000`).

Parquet offers 3 different precisions for timestamps (see https://github.com/apache/parquet-format/blob/master/LogicalTypes.md): microseconds, milliseconds and nanoseconds. Each come with their pros and cons (see the aforementioned parquet documentation for details on storage space and supported date range). You can explicitly select them using the following:
* `new Column<DateTime>("d1", LogicalType.Timestamp(true, TimeUnit.Micros))`
* `new Column<DateTime>("d1", LogicalType.Timestamp(true, TimeUnit.Millis))`
* `new Column<DateTimeNanos>("d1"))`

Take note that the last one uses a new type (`DateTimeNanos`) as `DateTime` does not have nanosecond precision. It is all a bit unfortunate that `DateTime` has high precision than milliseconds but lower precision than nanosecond, so there is no perfect mapping.

Ask yourself what precision you truly need in your application. I suspect you'll be fine with the default millisecond precision. It's just that your example using `DateTime.UtcNow` will not roundtrip properly in that case.

**Comment by GPSnoopy** [comment]
**Edited comment above** default precision for `DateTime` is microseconds, not milliseconds (proof that it's easy to get confused).

**Comment by vikramrkin** [comment]
Thanks for the help.
