### ISSUE TITLE
Just tried with Visual Studio 2022 .\vcpkg_windows.bat and failed

### ISSUE THREAD

**Issue by MironAtHome** [G-Research/ParquetSharp#251]
Messages:
F:\HL\dev\git\ParquetSharp>vcpkg_windows.bat

F:\HL\dev\git\ParquetSharp>for /F "tokens=1,2" %a in (vcpkg_version.txt) do (
set vcpkg_url=%a
 set vcpkg_ref=%b
)  || goto :error

F:\HL\dev\git\ParquetSharp>(
set vcpkg_url=https://github.com/microsoft/vcpkg.git
 set vcpkg_ref=0fcee5a2ab497b851f6dbf55dc052bcff2b05072
)  || goto :error

F:\HL\dev\git\ParquetSharp>set triplet=x64-windows-static

F:\HL\dev\git\ParquetSharp>mkdir build

F:\HL\dev\git\ParquetSharp>cd build   || goto :error

F:\HL\dev\git\ParquetSharp\build>rem Clone without checking out a branch, as vcpkg_ref could be a commit SHA

F:\HL\dev\git\ParquetSharp\build>git clone https://github.com/microsoft/vcpkg.git vcpkg.x64-windows-static   || goto :error
Cloning into 'vcpkg.x64-windows-static'...
remote: Enumerating objects: 141237, done.
remote: Counting objects: 100% (94/94), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 141237 (delta 81), reused 73 (delta 73), pack-reused 141143
Receiving objects: 100% (141237/141237), 50.82 MiB | 5.23 MiB/s, done.
Resolving deltas: 100% (88094/88094), done.
Updating files: 100% (8518/8518), done.

F:\HL\dev\git\ParquetSharp\build>cd vcpkg.x64-windows-static   || goto :error

F:\HL\dev\git\ParquetSharp\build\vcpkg.x64-windows-static>git checkout 0fcee5a2ab497b851f6dbf55dc052bcff2b05072   || goto :error
Updating files: 100% (2220/2220), done.
Note: switching to '0fcee5a2ab497b851f6dbf55dc052bcff2b05072'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 0fcee5a2a [arrow] Update to 6.0.1 (#22084)

F:\HL\dev\git\ParquetSharp\build\vcpkg.x64-windows-static>if "" == "true" echo set(VCPKG_BUILD_TYPE release)   1>>triplets\x64-windows-static.cmake  || goto :error

F:\HL\dev\git\ParquetSharp\build\vcpkg.x64-windows-static>call .\bootstrap-vcpkg.bat   || goto :error
Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2021-12-09/vcpkg.exe -> F:\HL\dev\git\ParquetSharp\build\vcpkg.x64-windows-static\vcpkg.exe... done.
Validating signature... done.

Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md
find_file_recursively_up(F:\HL\dev\git\ParquetSharp\build\vcpkg.x64-windows-static, .vcpkg-root): The parameter is incorrect.
Failed with error #1.

**Comment by MironAtHome** [comment]
Screenshot:
![image](https://user-images.githubusercontent.com/18360184/151830388-1fd56597-5520-4b65-be44-3600d69f510d.png)

**Comment by MironAtHome** [comment]
Looks like an vcpkg.exe related bug
https://www.giters.com/microsoft/vcpkg/issues/21107

**Comment by adamreeve** [comment]
Thanks for the bug report @MironAtHome, yes this does look like it's a vcpkg bug rather than something we can fix in ParquetSharp. That issue has a different error message ("Not a directory" rather than "The parameter is incorrect") but there's another open issue for the error you're seeing: https://github.com/microsoft/vcpkg/issues/19524

It sounds like this happens when running vcpkg in a drive that doesn't use the NTFS file system, so you should be able to work around this by moving your ParquetSharp directory to your C drive or another NTFS drive.

**Comment by BillyONeal** [comment]
This should be fixed in vcpkg now, can someone try with a recent-ish copy?

**Comment by adamreeve** [comment]
Thanks for following up on this @BillyONeal, I tested building ParquetSharp on a FAT32 drive with the latest Visual Studio 2022 installed and it does appear that this bug is fixed as some of the vcpkg dependencies were successfully built.

I wasn't actually able to get our full build to work though due to running into a different issue when extracting some zip files, which gave errors like:
```
CMake Error: Problem with archive_write_finish_entry(): Can't restore time
```
It looks like this has been reported already at https://github.com/microsoft/vcpkg/issues/28527. 

I could work around this problem for powershell-core by installing that myself, but ran into this again with strawberry-perl and installing that myself didn't seem to help, at which point I gave up.

I think we can close this particular bug as fixed but I'd recommend anyone trying to build ParquetSharp on Windows still avoids doing so on a FAT32 or exFAT drive if possible.
