### ISSUE TITLE
Broken io exceptions when testing

### ISSUE THREAD

**Issue by johnboy007** [G-Research/ParquetSharp#266]
While testing i am finding i am breaking the System Crash with something not disposing - implemented as shown on the wiki

Code is here [Repo](https://github.com/johnboy007/parquetsharp-test)

**### Error**
`[](https://github.com/johnboy007/parquetsharp-test#at-parquetsharpiorandomaccessfilerandomaccessfile_freeintptr)ParquetMapper_WithParquet_MapsProductGroups_Returns47 Aborted: Exit code is -2146232797 (Process terminated. A callback was made on a garbage collected delegate of type 'ParquetSharp!ParquetSharp.IO.ManagedRandomAccessFile+CloseDelegate::Invoke'. Repeat 2 times:
at ParquetSharp.IO.RandomAccessFile.RandomAccessFile_Free(IntPtr)
at ParquetSharp.ParquetHandle.Finalize())`

**Comment by adamreeve** [comment]
Hi @johnboy007, `ManagedRandomAccessFile` is `IDisposable`, so you should use it with a `using` block or statement. For example, at https://github.com/johnboy007/parquetsharp-test/blob/2da645837c254c18cce84b932ad9f58fc28f1609/ParquetMapper.cs#L183, you should instead use:
```C#
using var input = new ManagedRandomAccessFile(stream, true);
```

When the `ManagedRandomAccessFile` is passed in to the `ParquetFileReader` constructor, we don't internally keep hold of a reference to it but only use it to pass delegates for performing operations on the file through to the underlying C++ library, and these delegate references can't be tracked by the dotnet garbage collector when they're passed into unmanaged code so the `ManagedRandomAccessFile` is garbage collected while it is still needed.

When a `using` statement is used, the `ManagedRandomAccessFile` instance will be kept alive until the end of the code block when it will be disposed, so that should fix this error.

**Comment by johnboy007** [comment]
your the man - thank you
