### ISSUE TITLE
isAdjustedToUtc: false 

### ISSUE THREAD

**Issue by PhilevP** [G-Research/ParquetSharp#272]
Hello G-Research, 

I've been working on a project in order to convert data from an SQL-Server database to parquet, but I reach a wall when trying to remove the UTC from the DateTime column for the writer. I've read through other issues and found out that isAdjustedToUtc is set to default true, however the original data i have does not use UTC. If I try using `columns[i] = new Column<DateTime?>(cdt.Schema[i].Name, LogicalType.Timestamp(isAdjustedToUtc: false, timeUnit: TimeUnit.Nanos)` there is an exception since the values in the database are of type DateTime and there is a mismatch with the LogicalTypeOverride.

`System.NotSupportedException: 'unsupported logical system type System.Nullable1[System.DateTime] with logical type Timestamp(isAdjustedToUTC=false, timeUnit=nanoseconds, is_from_converted_type=false, force_set_converted_type=false)`

I posted the same question in StackOverflow a few days ago, but haven't gotten a conclusive answer, apart from using the ConverterFactory, and while i try using that based on the snippets provided I can't seem to get it working 
`converterFactory.GetConverter<DateTime, TimeSpanNanos>(columnDescriptor, byteBuffer: buffer) ;` 

To briefly summarize, I just want to take the DateTime values in the original database column and write them to the parquet file again as DateTime but without UTC. And since they are of the same type it feels redundant to use the LogicalFactories to cast DateTime as DateTime with no UTC. Is there an easier way or what is the best way to proceed? 

I know this is not a direct issue to the library itself, and more an issue on my part, but I would really appreciate any suggestions how to handle this instance.

**Comment by adamreeve** [comment]
Hi @PhilevP, I think the issue here might be that you are trying to use nanosecond time precision, but DateTimes don't support nanosecond precision. ParquetSharp provides a `DateTimeNanos` type that can be used instead, or you might want to switch to microsecond precision, eg. `columns[i] = new Column<DateTime?>(cdt.Schema[i].Name, LogicalType.Timestamp(isAdjustedToUtc: false, timeUnit: TimeUnit.Micros)`

**Comment by PhilevP** [comment]
Thank you for the response @adamreeve! Using `timeUnit: TimeUnit.Micros` allowed for the override with no UTC. A follow up if I were to use `DateTimeNanos` ParquetSharp type, I have to set up the `LogicalTypeFactory` and `LogicalWriteConverterFactory`, with the logical type being DateTime and the physical being DateTimeNanos as the TLogical is the readonly-span? 

`if (logicalSystemType == typeof(DateTime)) return base.TryGetParquetTypes(typeof(DateTimeNanos), out entry);`
  
`if (typeof(TLogical) == typeof(DateTime)) return LogicalWrite.GetNativeConverter<DateTime, DateTimeNanos>();`

**Comment by adamreeve** [comment]
You shouldn't need to configure your own `LogicalWriteConverterFactory` to use `DateTimeNanos`, the built in `LogicalTypeFactory` already maps `DateTimeNanos` to Timestamp columns with nanosecond precision, so it should just be a matter of defining your column as something like:
```C#
columns[i] = new Column<DateTimeNanos?>(cdt.Schema[i].Name, LogicalType.Timestamp(isAdjustedToUtc: false, timeUnit: TimeUnit.Nanos)
```
But then you would need to provide `DateTimeNanos` values when writing data.

If you wanted to be able to write normal `DateTime` values as Parquet nanosecond timestamps without first converting them to `DateTimeNanos`, then you would need to set up a custom `LogicalWriteConverterFactory`. In this case `TLogical` would be `DateTime` (or possibly `DateTime?` for nullable values), which is the type of values you want to write, and `TPhysical` is `long`, as Timestamps in Parquet are always written as int64 physical values.

You then just need to define how to convert a `DateTime` into a nanosecond timestamp value, with something like:
```C#
private sealed class DateTimeNanosWriteConverterFactory : LogicalWriteConverterFactory
{
    public override Delegate GetConverter<TLogical, TPhysical>(ColumnDescriptor columnDescriptor, ByteBuffer? byteBuffer)
    {
        if (typeof(TLogical) == typeof(DateTime) && ((TimestampLogicalType) columnDescriptor.LogicalType).TimeUnit == TimeUnit.Nanos)
        {
            return (LogicalWrite<DateTime, long>.Converter) ((source, _, dest, _) => ConvertDateTimeNanos(source, dest));
        }
        return base.GetConverter<TLogical, TPhysical>(columnDescriptor, byteBuffer);
    }
    
    private static void ConvertDateTimeNanos(ReadOnlySpan<DateTime> source, Span<long> destination)
    {
        for (int i = 0; i < source.Length; ++i)
        {
            destination[i] = (source[i].Ticks - LogicalWrite.DateTimeOffset) * (1_000_000 / TimeSpan.TicksPerMillisecond);
        }
    }
}
```
Note that this doesn't handle nullable values. And because `DateTime` is already mapped to the `long` physical type you shouldn't need to implement a `LogicalTypeFactory`.

**Comment by vthemelis** [comment]
Hi @adamreeve ,

Is there a quick way to force TimeZone naïve timestamps in,say, an array of DateTimes?

**Comment by adamreeve** [comment]
Hi @vthemelis, can you explain more what you're trying to achieve? It sounds like you have an array of DateTimes and you want to write them as TimeZone naive timestamps in a Parquet file, so you should just be able to specify `isAdjustedToUtc: false` in the logical type.

If instead you're talking about reading DateTime values from a Parquet file and you want them to have `Kind` set to `DateTimeKind.Unspecified` you can use the `ParquetSharp.ReadDateTimeKindAsUnspecified` AppContext switch that was added in #288

**Comment by vthemelis** [comment]
Oh, sorry, I misunderstood the purpose of the logical type. I thought that I would have to provide a logical type representing an array (or list as in `LogicalType.List()`) of DateTimes as the last argument to the `Column` ctor.

Looks like just passing the logical type for the leaf type of the array is enough.

Thanks!
