### ISSUE TITLE
Row based read access

### ISSUE THREAD

**Issue by azuric** [G-Research/ParquetSharp#72]
Hi,

Can you post some code to show how you would read a parquet file row by row? 

Regards

**Comment by GPSnoopy** [comment]
Hi @azuric,

Due to the fact that Parquet files are column oriented, the low-level C++ API of Arrow Parquet allows you to only read a chunk of a column at a time. 

ParquetSharp does have a row-oriented API that reads and gives you all the rows in a row group in one go at the expense of more memory buffering (same for the writer). It mostly serves as an example and a quick & dirty tool to get started rather than the intended usage.

See implementation:
https://github.com/G-Research/ParquetSharp/blob/master/csharp/RowOriented/ParquetRowReader.cs

And usage example here:
https://github.com/G-Research/ParquetSharp/blob/master/csharp.test/TestRowOrientedParquetFile.cs

In practice, an application that needs finer control should use the low-level API directly and batch-read chunks of each columns, with a buffer size that suits its needs best.

I hope this helps.
